### ISSUE TITLE
在minSdkVersion=17的手机上跑不起来~

### ISSUE THREAD

**Issue by Dreamxhx** [codeestX/GeekNews#109]
本人把你的最小支持的sdk改成15，在17的手机上跑起来直接崩溃了，6.0手机没有问题，报错如下：
  android.view.InflateException: Binary XML file line #10: Error inflating class com.codeest.geeknews.widget.ProgressImageView
at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                          at android.view.View.inflate(View.java:16617)
                                                                          at com.codeest.geeknews.base.RootFragment.initEventAndData(RootFragment.java:46)

请问是什么原因呢？

**Comment by Dreamxhx** [comment]
这个控件没有改过~

**Comment by wangxiaofan** [comment]
加载ProgressImageView动画引起的，项目中animated-vector只能在api21以上才能跑起来
