### ISSUE TITLE
How to cancel request?

### ISSUE THREAD

**Issue by Widiyanto** [codeestX/GeekNews#120]
When the process is running to load data, I close the fragment and got error.
821-821/id.jkt.wot E/AndroidRuntime: FATAL EXCEPTION: main
                                                        Process: id.jkt.wot, PID: 821
                                                        java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                            at android.os.Looper.loop(Looper.java:135)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                         Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void id.jkt.wot.base.contract.InsuranceNameContract$View.showContent(id.jkt.wot.model.bean.GeneralCategoryBean)' on a null object reference
                                                            at id.jkt.wot.presenter.own.InsuranceNamePresenter$1.onNext(InsuranceNamePresenter.java:32)
                                                            at id.jkt.wot.presenter.own.InsuranceNamePresenter$1.onNext(InsuranceNamePresenter.java:29)
                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                            at android.os.Looper.loop(Looper.java:135) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by Widiyanto** [comment]
mCompositeDisposable.clear();
