### ISSUE TITLE
空指针了

### ISSUE THREAD

**Issue by HYVincent** [codeestX/GeekNews#29]
2-03 16:04:13.345 12377-12377/com.codeest.geeknews E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.codeest.geeknews, PID: 12377
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
                                                                          at com.codeest.geeknews.ui.gank.activity.TechDetailActivity$2.onProgressChanged(TechDetailActivity.java:91)
                                                                          at com.tencent.smtt.sdk.SystemWebChromeClient.onProgressChanged(Unknown Source)
                                                                          at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:236)
                                                                          at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:197)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:150)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5665)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

空指针 com.codeest.geeknews.ui.gank.activity.TechDetailActivity  tvProgress非空验证 setVisibility和getLayoutParams方法返回空指针了

**Comment by codeestX** [comment]
@HYVincent 感谢反馈，我会查下这个问题，在下个版本修复

**Comment by codeestX** [comment]
@HYVincent 已更新至v1.2.0版本
