### ISSUE TITLE
TechAdapter doblur got OOM

### ISSUE THREAD

**Issue by mavsforlife** [codeestX/GeekNews#5]
java.lang.OutOfMemoryError: Failed to allocate a 25165836 byte allocation with 16565788 free bytes and 15MB until OOM
                                                                          at com.codeest.geeknews.util.ImageUtil.doBlur(ImageUtil.java:64)
                                                                          at com.codeest.geeknews.ui.gank.adapter.TechAdapter$2.onResourceReady(TechAdapter.java:105)
                                                                          at com.codeest.geeknews.ui.gank.adapter.TechAdapter$2.onResourceReady(TechAdapter.java:101)
                                                                          at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
                                                                          at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
                                                                          at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
                                                                          at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
                                                                          at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by codeestX** [comment]
@mavsforlife Hello, mavsforlife.The current blur algorithm is not good enough, RenderScript is the best way for Android to blur a bitmap.I have tried it ,but did not get the expected result. I'm still trying to find a solution.

**Comment by jp1017** [comment]
同遇到此问题
