### ISSUE TITLE
一直点击切换夜间模式会crash

### ISSUE THREAD

**Issue by ForLovelj** [codeestX/GeekNews#8]
一直点击切换夜间模式会crash，报了一个空指针。还有就是怎么一直没数据，服务器502

**Comment by codeestX** [comment]
@ForLovelj 你好，可以提供下空指针的错误日志么？ 微信精选API可能是访问量到了上限，所以没有返回数据，已经更换了新的API

**Comment by rickyin** [comment]
```
03-13 16:15:20.187 3541-3573/com.codeest.geeknews E/EGL_emulation: tid 3573: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
03-13 16:15:20.964 3541-3573/com.codeest.geeknews E/EGL_emulation: tid 3573: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
03-13 16:15:21.125 3541-3541/com.codeest.geeknews E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.codeest.geeknews, PID: 3541
                                                                    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                     Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
                                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
                                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204) 
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144) 
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227) 
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                        at android.util.Log.printlns(Log.java:415)
                                                                        at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                        at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.codeest.geeknews.presenter.contract.ThemeContract$View.showContent(com.codeest.geeknews.model.bean.ThemeListBean)' on a null object reference
                                                                        at com.codeest.geeknews.presenter.ThemePresenter$1.onNext(ThemePresenter.java:32)
                                                                        at com.codeest.geeknews.presenter.ThemePresenter$1.onNext(ThemePresenter.java:29)
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.widget.SwipeRefreshLayout.isRefreshing()' on a null object reference
                                                                        at com.codeest.geeknews.ui.zhihu.fragment.ThemeFragment.showError(ThemeFragment.java:86)
                                                                        at com.codeest.geeknews.widget.CommonSubscriber.onError(CommonSubscriber.java:44)
                                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227) 
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
03-13 16:15:21.229 1512-3467/system_process E/EGL_emulation: tid 3467: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
03-13 16:15:21.688 1247-1247/? E/EGL_emulation: tid 1247: eglCreateSyncKHR(1641): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-13 16:15:21.883 1975-2122/com.android.launcher3 E/EGL_emulation: tid 2122: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)

```
