### ISSUE TITLE
息屏一段时间会出现这个错误，机型努比亚z11

### ISSUE THREAD

**Issue by mycold** [codeestX/GeekNews#85]
05-08 15:25:47.217 13592-13592/com.codeest.geeknews E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.codeest.geeknews, PID: 13592
                                                                      io.reactivex.exceptions.OnErrorNotImplementedException: Can't deliver value 128 due to lack of requests
                                                                          at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
                                                                          at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
                                                                          at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:76)
                                                                          at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:207)
                                                                          at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:392)
                                                                          at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                          at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:171)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5681)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
                                                                       Caused by: io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 128 due to lack of requests
                                                                          at io.reactivex.internal.operators.flowable.FlowableInterval$IntervalSubscriber.run(FlowableInterval.java:87)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                          at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:154)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by codeestX** [comment]
@mycold Hello，感谢提供日志，应该是`Flowable.interval`引发的问题，做了一些处理 53dd815
