### ISSUE TITLE
Session 'app' error while installing APK

### ISSUE THREAD

**Issue by Widiyanto** [codeestX/GeekNews#90]
Thanks a lot, great app.
When running get error Session 'app' error while installing APK.

**Comment by Widiyanto** [comment]
The currently selected variant "google-debug" uses split APKs, but none of the 4 split apks are compatible with the current device with density "320" and ABIs "x86".
Error while Installing APK

**Comment by Widiyanto** [comment]
An established connection was aborted by the software in your host machine java.io.IOException: An established connection was aborted by the software in your host machine at sun.nio.ch.SocketDispatcher.write0(Native Method) at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) at sun.nio.ch.IOUtil.write(IOUtil.java:65) at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) at com.android.ddmlib.JdwpPacket.write(JdwpPacket.java:179) at com.android.ddmlib.Client.send(Client.java:654) at com.android.ddmlib.jdwp.JdwpAgent.send(JdwpAgent.java:92) at com.android.ddmlib.HandleHeap.sendREAQ(HandleHeap.java:349) at com.android.ddmlib.Client.requestAllocationStatus(Client.java:517) at com.android.ddmlib.DeviceMonitor.createClient(DeviceMonitor.java:573) at com.android.ddmlib.DeviceMonitor.openClient(DeviceMonitor.java:545) at com.android.ddmlib.DeviceMonitor.processIncomingJdwpData(DeviceMonitor.java:507) at com.android.ddmlib.DeviceMonitor.deviceClientMonitorLoop(DeviceMonitor.java:403) at com.android.ddmlib.DeviceMonitor.access$100(DeviceMonitor.java:65) at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:326)
