### ISSUE TITLE
进不去，直接crash

### ISSUE THREAD

**Issue by senlinxuefeng** [codeestX/GeekNews#94]
06-09 11:36:03.714 18485-18578/com.codeest.geeknews E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                      Process: com.codeest.geeknews, PID: 18485
                                                                      io.reactivex.exceptions.UndeliverableException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/blueware/agent/android/instrumentation/okhttp3/OkHttp3Instrumentation;
                                                                          at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:62)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/blueware/agent/android/instrumentation/okhttp3/OkHttp3Instrumentation;
                                                                          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at com.codeest.geeknews.di.module.HttpModule$1.intercept(HttpModule.java:119)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                          at okhttp3.RealCall.execute(RealCall.java:63)
                                                                          at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                          at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
                                                                          at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                                          at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                          at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                                          at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
                                                                          at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                          at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
                                                                          at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                          at io.reactivex.Flowable.subscribe(Flowable.java:12917)
                                                                          at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blueware.agent.android.instrumentation.okhttp3.OkHttp3Instrumentation" on path: DexPathList[[zip file "/data/app/com.codeest.geeknews-1/base.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.codeest.geeknews-1/split_lib_slice_7

**Comment by codeestX** [comment]
@senlinxuefeng 你贴出的错误日志里有这句包名`com/blueware/agent`，GeekNews里没有和这个包名相关的内容，应该是受到了手机上其他应用或者SDK的影响

参考这里：https://stackoverflow.com/questions/39010863/application-interceptor-com-blueware-agent-android-instrumentation-okhttp3-d41c
