### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by HuuNguyen312** [codeestX/GeekNews#96]
java.lang.OutOfMemoryError: Failed to allocate a 982476 byte allocation with 248096 free bytes and 242KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:825)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:802)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:769)
	at android.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:134)
	at android.app.SharedElementCallback.onCaptureSharedElementSnapshot(SharedElementCallback.java:150)
	at android.app.ActivityTransitionCoordinator.captureSharedElementState(ActivityTransitionCoordinator.java:671)
	at android.app.ActivityTransitionCoordinator.captureSharedElementState(ActivityTransitionCoordinator.java:596)
	at android.app.ExitTransitionCoordinator.sharedElementTransitionComplete(ExitTransitionCoordinator.java:384)
	at android.app.ExitTransitionCoordinator.access$1400(ExitTransitionCoordinator.java:43)
	at android.app.ExitTransitionCoordinator$10.onTransitionEnd(ExitTransitionCoordinator.java:345)
	at android.transition.Transition.end(Transition.java:1890)
	at android.transition.TransitionSet$TransitionSetListener.onTransitionEnd(TransitionSet.java:378)
	at android.transition.Transition.end(Transition.java:1890)
	at android.transition.TransitionSet$TransitionSetListener.onTransitionEnd(TransitionSet.java:378)
	at android.transition.Transition.end(Transition.java:1890)
	at android.transition.Transition.runAnimators(Transition.java:869)
	at android.transition.TransitionSet.runAnimators(TransitionSet.java:442)
	at android.transition.TransitionSet.runAnimators(TransitionSet.java:442)
	at android.transition.Transition.playTransition(Transition.java:1762)
	at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:298)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2332)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1284)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6490)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
	at android.view.Choreographer.doCallbacks(Choreographer.java:605)
	at android.view.Choreographer.doFrame(Choreographer.java:574)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by codeestX** [comment]
It seems that ShareElement Animation tried to use more memory than what was available. But i don't know the root cause.
